### ISSUE TITLE
Just a though, what do you mean for vanilla?

### ISSUE THREAD

**Issue by equinusocio** [Granze/flip-clock-vanilla#1]
Just a though, but i think this is not a vanilla wc because it needs a some third-party libs. A vanilla wc should be "plug-and-play" not "plug-compile-and-play."

Since this code needs a bundler/transpiler to works i think is wrong to call it "vanilla". The builded code will be a "vanilla js".

What do you think @Granze? Taking this component as example https://github.com/contactlab/ikonograph/blob/master/src/ikonograph.js that are "plug-and-play" and platform-compliant. If i want to use ikonograph, i have just to include his js file and start using it also in a plain HTML file.

How i can do that whit this component without a bundler?

**Comment by Granze** [comment]
Hi @equinusocio, 
"vanilla WC" means that no libraries or frameworks has been used to build the WC itself.  
ES2015 is just vanilla javascript so, the fact you need to transpile it, depends on the target platform. 
Bundler and transpiler are needed just during development, if you want to use something that is "plug-and-play", you can just grab the [bundle.js](https://github.com/Granze/flip-clock-vanilla/blob/master/bundle.js). 
Anyway, in a modern web app you will probably want to use the WC as an NPM module. ;)

**Comment by equinusocio** [comment]
> Anyway, in a modern web app you will probably want to use the WC as an NPM module. ;)

But web components were born to be framwork/library independent and i think you can't assume to use it only inside a npm-project.

Since you shipped it only through npm i have to manually download the bundle.js file for every update/fix. Is not so good for a component born to be deliverable :) Maybe an alternative platform-compliant method like a CDN script can "complete" the component and allow it to be used inside a non-npm project.

**NOTE:** You also used hyperHTML library, a npm  dependency that render the template and must be precompiled (ES2015 or not). So i think that only the bundle.js is a vanilla component, not the source because it don't use a standard way to render the wc template :)

**Comment by Granze** [comment]
If you want to always use the updated version or have control over a
particular one, you should use a proper package manager, like NPM. And
flip-click it's available as a package
https://www.npmjs.com/package/flip-clock-vanilla.

If, for some reasons, you want (or you have) to use a non NPM version, yes
you will have to update the component by yourself downloading or pointing
to the latest version. Like the ol' good days. :)
