### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by equinusocio** [Granze/flip-clock-vanilla#2]
Hi, the demo does not works. It shows the `<pre>` code.

**Comment by Celestz** [comment]
![image](https://user-images.githubusercontent.com/1031789/38982464-807c007c-43f4-11e8-8fba-7f7fff0aa32e.png)
@equinusocio  I can see the demo find on your end, does your console throw any errors?

**Comment by equinusocio** [comment]
Now i can see it. I don't know what's happened.
